// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpGPILwFDvSfvO1HfpOVCQHnr23sXqWfs',
    appId: '1:737368336780:web:61646522bcc4fc1c674ea9',
    messagingSenderId: '737368336780',
    projectId: 'otp-code-verification-pr-c930d',
    authDomain: 'otp-code-verification-pr-c930d.firebaseapp.com',
    storageBucket: 'otp-code-verification-pr-c930d.appspot.com',
    measurementId: 'G-BQ2LXGG0NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwZmjzju6kXpSCUVDucayUMgtRD7VtnE',
    appId: '1:737368336780:android:2ec8417d42ee22bf674ea9',
    messagingSenderId: '737368336780',
    projectId: 'otp-code-verification-pr-c930d',
    storageBucket: 'otp-code-verification-pr-c930d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB26Nm8mSFNR-ib7OKn7RYJbPTarLWFOrA',
    appId: '1:737368336780:ios:5753ad0fa680cdda674ea9',
    messagingSenderId: '737368336780',
    projectId: 'otp-code-verification-pr-c930d',
    storageBucket: 'otp-code-verification-pr-c930d.appspot.com',
    iosClientId: '737368336780-koei02g4acdse9776qpguo3rcsk68stt.apps.googleusercontent.com',
    iosBundleId: 'com.example.otpCodeVerification',
  );
}
